apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-secret-server
  namespace: apps
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-secret-server
  template:
    metadata:
      labels:
        app: echo-secret-server
    spec:
      containers:
      - name: echo-secret-server
        image: echo-secret-server:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: SUPER_SECRET
          valueFrom:
            secretKeyRef:
              name: super-secret
              key: SUPER_SECRET
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: super-secret