apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: super-secret
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: gcpsm-secret-store
  target:
    name: super-secret
    creationPolicy: Owner
  data:
  - secretKey: SUPER_SECRET
    remoteRef:
      key: SUPER_SECRET