apiVersion: v1
kind: Service
metadata:
  name: echo-secret-server
  namespace: apps
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30030
  selector:
    app: echo-secret-server
