apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies-crds
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 3.1.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true