apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: reloader
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com'
    targetRevision: HEAD
    path: 'stakater/Reloader/master/deployments/kubernetes/reloader.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
