{{- range $key, $value := .Values.secrets }}
apiVersion: actions.github.upbound.io/v1alpha1
kind: ActionsSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower | replace "_" "-" }}
spec:
  forProvider:
    plaintextValueSecretRef:
      key: {{ $key }}
      name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower | replace "_" "-" }}
      namespace: {{ $.Release.Namespace }}
    secretName: {{ $key }}
    repositorySelector: 
      matchLabels: 
        pillar: {{ $.Values.pillar }}
  providerConfigRef:
    name: provider-config-github
{{- end }}