{{- range $key, $value := .Values.secrets }}
apiVersion: actions.github.upbound.io/v1alpha1
kind: ActionsSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower }}
spec:
  forProvider:
    plaintextValueSecretRef: {{ $value }}
    secretName: {{ $key }}
    repositorySelector: 
      matchLabels: {{ printf "pillar: %s" $.Values.pillar }}
  providerConfigRef:
    name: provider-config-github
{{- end }}