{{- range $key, $value := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}