apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: {{ include "repos-helm.fullname" . }}
spec:
  forProvider:
    gitignoreTemplate: VisualStudio
    visibility: private
    autoInit: true
  providerConfigRef:
    name: provider-config-github