{{- $combinedSecrets := merge .Values.secrets .Values.pillarSecrets }}
{{- range $key, $value := $combinedSecrets }}
---
apiVersion: actions.github.upbound.io/v1alpha1
kind: ActionsSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower | replace "_" "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  forProvider:
    plaintextValueSecretRef:
      key: {{ $key }}
      name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower | replace "_" "-" }}
      namespace: {{ $.Release.Namespace }}
    secretName: {{ $key }}
    repository: {{ $.Release.Name }}
  providerConfigRef:
    name: provider-config-github 
{{- end }}