{{- $combinedSecrets := append .Values.secrets .Values.pillarSecrets }}
{{- range $key, $value := $combinedSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower | replace "_" "-" }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}