{{- $combinedSecrets := merge .Values.secrets .Values.pillarSecrets }}
{{- range $key, $value := $combinedSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower | replace "_" "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcpsm-secret-store
  target:
    name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | lower | replace "_" "-" }}
    creationPolicy: Owner
  data:
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $value }}  
{{- end }}