apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: crossplane-test-example-1
  label:
    pillar: "Developer-Acceleration"
spec:
  forProvider:
    gitignoreTemplate: VisualStudio
    visibility: private
    autoInit: true
  providerConfigRef:
    name: provider-config-github
